### PR TITLE
Ben Lovell - Fast, testable and SANE APIs!

### PR DESCRIPTION
**Pull request by benlovell**
By now, we've all written JSON APIs in Rails. But how do you write fast, testable and sane APIs? I'll guide you through the trials of designing and building awesome, scalable APIs. We'll cover rails-api, active model serializers, and all the associated goodness that our ecosystem has to offer.

I'll speak on the approaches to authentication, how to ensure we remain good REST/HTTP citizens and maybe if I have time I'll share some of my top secret beard grooming tips!

### CODE REVIEW

**Comment by stream7** [comment]
+1

**Comment by andypike** [comment]
:+1:

**Comment by fuzzmonkey** [comment]
+1

**Comment by patshaughnessy** [comment]
+1

**Comment by alco** [comment]
LGTM :+1:

**Comment by chattsm** [comment]
:+1:

**Comment by zorbash** [comment]
:+1:

**Comment by jongilbraith** [comment]
:+1:

**Comment by MoritzBecker** [comment]
:+1:

**Pull request closed without merging**
